ENH: Add API to select items in the DICOM browser
commontk/CTK pull request #1002
Opened 2021-11-03 18:22 UTC by lassoan

Allow selecting patient/study/series in the DICOM browser GUI.

This is can be used for example for highlighting new items after DICOM import.

2021-11-03 19:25 UTC, pieper approved these changes
LGTM 👍

2021-11-03 19:32 UTC, jcfr requested changes

2021-11-03 19:32 UTC, jcfr commented on Libs/DICOM/Widgets/ctkDICOMTableManager.cpp
> +  return d->patientsTable->setCurrentSelection(uids);
```suggestion
  d->patientsTable->setCurrentSelection(uids);
```

2021-11-03 19:32 UTC, jcfr commented on Libs/DICOM/Widgets/ctkDICOMTableManager.cpp
> +  return d->studiesTable->setCurrentSelection(uids);
```suggestion
  d->studiesTable->setCurrentSelection(uids);
```

2021-11-03 19:32 UTC, jcfr commented on Libs/DICOM/Widgets/ctkDICOMTableManager.cpp
> +  return d->seriesTable->setCurrentSelection(uids);
```suggestion
  d->seriesTable->setCurrentSelection(uids);
```

2021-11-03 19:33 UTC, jcfr commented
Consider rebasing the topic so that we avoid commit like `Merge branch 'master' into add-dicombrowser-select-api` making it hard to cherry-pick or revert changes.

2021-11-03 19:34 UTC, pieper commented
@lassoan github reported this was out of date with master so I merged it and there are no conflicts but I wondered why you hadn't started from the master branch?  Maybe better to rebase instead of squash as @jcfr suggests.

2021-11-03 21:01 UTC, lassoan commented
> I wondered why you hadn't started from the master branch?

No specific reason, it was just what I had in my build tree.

Thanks for the review and comments, I'll rebase on latest master.

2021-11-03 21:12 UTC, jcfr commented on Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
> +    for (QString uid : uids)
For correctness:

```suggestion
    for (const QString& uid : uids)
```

https://stackoverflow.com/questions/15176104/range-based-loop-get-item-by-value-or-reference-to-const/15176127#15176127

2021-11-03 21:12 UTC, jcfr commented on Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
> +    for (QString uid : uids)
```suggestion
    for (const QString& uid : uids)
```

2021-11-04 02:24 UTC, lassoan commented
@jcfr I've updated ctkDICOMTableView::setCurrentSelection to use `d->tblDicomDatabaseView->selectionModel()->isSelected(index)`, because selection mode is "full row", so it is enough to check that the item in the first column is selected.

2021-11-04 15:56 UTC, lassoan commented
@jcfr Thanks for your comments, I addressed all of them, let me know if this is good to go now.

2021-11-04 16:07 UTC, merged